Fix calling class with service_ensure stopped
root-expert/puppet-snap pull request #11
Opened 2023-02-22 13:25 UTC by bparak

#### Pull Request (PR) description
Using the `snap` provider inside the `snap` class prevents us from using the class to stop `snapd` itself. Since this seems to be sort of supported based on params, this simple conditional fixes the problem.

#### This Pull Request (PR) fixes the following issues
n/a (none open on this repo)

2023-02-28 10:12 UTC, root-expert requested changes
Hello @bparak and thanks for the PR!

Please rebase with master branch since I pushed some commits to fix the CI pipeline.

2023-02-28 10:12 UTC, root-expert commented on manifests/init.pp
> +      require  => Package['net_http_unix'],
Package core requires `snapd` daemon to be running

```suggestion
      require  => [Package['net_http_unix'], Service['snapd']],
```

2023-02-28 17:01 UTC, bparak commented
Hi @root-expert ,
Suggestion accepted and branched rebased.

2023-03-01 09:13 UTC, root-expert approved these changes
Thanks!

2023-03-01 09:13 UTC, merged